### PR TITLE
feat: Support additional metadata for controller

### LINKED ISSUE #16: Provide metadata for rollout controller resource
Hi,

It would be nice to be able to provide labels and annotations to the rollout controller generated from the Rollout Manager

### PR DESCRIPTION
**Pull request by OpenGuidou**
Fixes #16

### CODE REVIEW

**Comment by OpenGuidou** [comment]
Hi @iam-veeramalla , can I get a review on this change ?

**Comment by OpenGuidou** [comment]
Or @jgwest  ?

**Comment by OpenGuidou** [comment]
Tests should be fixed now

**Comment by OpenGuidou** [comment]
Hi @jgwest ,
Can I hope for a review on this one  ?

**Comment by harrietgrace** [comment]
@jgwest could you give this PR a review plz? 🙇🏻

**Review by jgwest — CHANGES_REQUESTED** [review]
Thanks for your patience, @OpenGuidou! Happy to say the operator is finally in good shape, and we are now able to accept PRs that are outside the operator's initial, essential GA functionality (These were [cluster-scoped support, unit tests, E2E tests, build improvements, etc](https://github.com/argoproj-labs/argo-rollouts-manager/pulls?q=is%3Apr+is%3Aclosed) )

Your PR looks great, and looks like a useful feature to add, I just have a question around the implementation.
	
#### What was the criteria used to determine which resources to apply the `.spec.controllerMetadata` labels/annotations to? 

In this PR, it appears that labels/annotations that are defined in `.spec.controllerMetadata` will be applied to these generated resources:
- Deployment + Pods of that Deployment (via PodSpec)
- RoleBinding
- Service (for metrics)

But labels/annotations will not be applied to these generated resources:
- ConfigMap
- ClusterRoleBinding
- ServiceAccount
- Role
- ClusterRole

(Correct me if I am wrong)

I don't see a pattern: I would assume  that the user's expectation would be that the labels/annotations are applied to all resources, for example, rather than just Deployment/RoleBinding/Service. Likewise, it seems to inconsistent to apply the labels/annotations only to RoleBinding and not ClusterRoleBinding.

Was this intentional, or (I'm guessing) is just because it was based on an older version of the code where some of these resources didn't exist?

**Comment by OpenGuidou** [comment]
> Thanks for your patience, @OpenGuidou! Happy to say the operator is finally in good shape, and we are now able to accept PRs that are outside the operator's initial, essential GA functionality (These were [cluster-scoped support, unit tests, E2E tests, build improvements, etc](https://github.com/argoproj-labs/argo-rollouts-manager/pulls?q=is%3Apr+is%3Aclosed) )
> 
> Your PR looks great, and looks like a useful feature to add, I just have a question around the implementation.
> 
> #### What was the criteria used to determine which resources to apply the `.spec.controllerMetadata` labels/annotations to?
> In this PR, it appears that labels/annotations that are defined in `.spec.controllerMetadata` will be applied to these generated resources:
> 
> * Deployment + Pods of that Deployment (via PodSpec)
> * RoleBinding
> * Service (for metrics)
> 
> But labels/annotations will not be applied to these generated resources:
> 
> * ConfigMap
> * ClusterRoleBinding
> * ServiceAccount
> * Role
> * ClusterRole
> 
> (Correct me if I am wrong)
> 
> I don't see a pattern: I would assume that the user's expectation would be that the labels/annotations are applied to all resources, for example, rather than just Deployment/RoleBinding/Service. Likewise, it seems to inconsistent to apply the labels/annotations only to RoleBinding and not ClusterRoleBinding.
> 
> Was this intentional, or (I'm guessing) is just because it was based on an older version of the code where some of these resources didn't exist?

You are right, I tried to add it everywhere but I guess the Cluster resources didn't exist then.
I can add them and rename the field as well to not only talk about the controller

**Comment by OpenGuidou** [comment]
@jgwest Done now, let me know what you think about it.

**Review by jgwest — APPROVED** [review]
Looks great, thanks again for your patience/persistence with us :sweat_smile: , and thanks for your quick response to review comments!

**Pull request merged**
